### ISSUE TITLE
Ran into an issue with :PackerCompile, says to check config for correctness

### ISSUE THREAD

**Issue by ragdoll2iguess** [shaunsingh/nyoom.nvim#1]
I recently updated neovim to the latest stable release on Void linux, and switched to the latest release of nyoom.nvim

When compiling packer after deleting packer_compiled, I get the following error:

> [packer.nvim] [ERROR 01:06:35] a... Reverse range in character classError in packer_compiled: /home/...ker.nvim/lua/packer/async.lua:11>Please check your config for correctness

Afterwards, whenever opening nvim, the following error comes up:

> Error in packer_compiled: /home/natalie/.config/nvim/lua/packer_compiled.lua:550: Vim(source):E5113:
 Error while calling lua chunk: .../nvim/site/pack/packer/opt/orgmode/ftdetect/filetype.lua:1: attempt to index field 'filetype' (a nil value)^@\stack traceback:^@^I.../nvim/site/pack/packer/opt/orgmod
e/ftdetect/filetype.lua:1: in main chunk^@^I[C]: in function 'cmd'^@^I/home/natalie/.config/nvim/lua
/packer_compiled.lua:550: in function </home/natalie/.config/nvim/lua/packer_compiled.lua:10>^@^I[C]
: in function 'pcall'^@^I/home/natalie/.config/nvim/lua/packer_compiled.lua:10: in main chunk^@^I[C]
: at 0x7f1b27f407d0^@^I[C]: in function 'pcall'^@^I/home/natalie/.config/nvim/init.lua:52: in main chunk
Please check your config for correctness
Error detected while processing BufReadPost Autocommands for "*":
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echo
msg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/pac
ker/load.lua:139: Vim(packadd):E5113: Error while calling lua chunk: .../nvim/site/pack/packer/opt/o
rgmode/ftdetect/filetype.lua:1: attempt to index field 'filetype' (a nil value)
stack traceback:
        [C]: in function 'cmd'   ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>

I tried this with both a modified version of the config, with the things that I needed in it personally, and then again completely raw, directly from github. I ran into the exact same issue, the exact same errors.

**Comment by shaunsingh** [comment]
This was because I moved to `filetype.lua` which is only in neovim nightly (while filetype.nvim was a plugin). I'll push a change making filetype.lua only for neovim nightly users. In the meantime, you can delete those two lines in `init.lua`

**Comment by shaunsingh** [comment]
I've since redone the whole config, I don't think this issue should occur any more
