### ISSUE TITLE
Base16 IBM Light Theme from shaunsingh/nix-darwin-dotfiles screenshot

### ISSUE THREAD

**Issue by first-logician** [shaunsingh/nyoom.nvim#10]
Hi shaunsingh,

Could you share the Base16 IBM Light Theme also in that config.

Regards,
steale

**Comment by shaunsingh** [comment]
The theme in that config is actually nano-light, from https://github.com/rougier/nano-theme. I wrote a basic (a bit broken/oudtated at the moment) version of the theme for neovim here: https://github.com/shaunsingh/nyoom.nvim/tree/5ecbcec6544ec6b5759364c665bc7c1f28acfa20/lua/ext/nano. I'll add it to nyoom sometime if you want!
