### ISSUE TITLE
module 'cmp' not found

### ISSUE THREAD

**Issue by xiaobing-huang** [shaunsingh/nyoom.nvim#11]
Hello shaunsingh,

I am encountering below error after switch to insert mode in neovim:
_Error detected while processing InsertEnter Autocommands for "*":
E5108: Error executing lua ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:48: module 'cmp' not found:
        no field package.preload['cmp']
        no file '/Users/xxxx/.cache/nvim/hotpot//Users/xxxx/.local/share/nvim/site/pack/packer/start/hotpot.nvim/fnl/cmp.lua'
        no file '/Users/xxxx/.luarocks/share/lua/5.3/cmp.lua'
        no file '/Users/xxxx/.luarocks/share/lua/5.3/cmp/init.lua'
        no file '/Users/xxxx/.asdf/installs/lua/5.3.6/luarocks/share/lua/5.3/cmp.lua'
        no file '/Users/xxxx/.asdf/installs/lua/5.3.6/luarocks/share/lua/5.3/cmp/init.lua'
        no file '/usr/local/Cellar/luarocks/3.7.0/share/lua/5.3/cmp.lua'
        no file '/Users/xxxx/.asdf/installs/lua/5.3/luarocks/share/lua/5.3/cmp.lua'
        no file '/Users/xxxx/.asdf/installs/lua/5.3/luarocks/share/lua/5.3/cmp/init.lua'
        no file '/usr/local/share/lua/5.3/cmp.lua'
        no file '/usr/local/share/lua/5.3/cmp/init.lua'
        no file '/usr/local/lib/lua/5.3/cmp.lua'
        no file '/usr/local/lib/lua/5.3/cmp/init.lua'
        no file './cmp.lua'
        no file './cmp/init.lua'
        no file '/Users/xxxx/.asdf/installs/lua/5.3/share/lua/5.3/cmp.lua'
        no file '/Users/xxxx/.asdf/installs/lua/5.3/share/lua/5.3/cmp/init.lua'
        no file '/Users/xxxx/.asdf/installs/lua/5.3.6/share/lua/5.3/cmp.lua'
        no file '/Users/xxxx/.asdf/installs/lua/5.3.6/share/lua/5.3/cmp/init.lua'
        no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp.lua'
        no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp/init.lua'
        no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp.lua'
        no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp/init.lua'
        no file '/Users/xxxx/.luarocks/lib/lua/5.3/cmp.so'
        no file '/Users/xxxx/.asdf/installs/lua/5.3.6/luarocks/lib/lua/5.3/cmp.so'
        no file '/Users/xxxx/.asdf/installs/lua/5.3/luarocks/lib/lua/5.3/cmp.so'
        no file '/usr/local/lib/lua/5.3/cmp.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './cmp.so'
        no file '/Users/xxxx/.asdf/installs/lua/5.3/lib/lua/5.3/cmp.so'
        no file '/Users/xxxx/.asdf/installs/lua/5.3.6/lib/lua/5.3/cmp.so'
        no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/cmp.so'
stack traceback:
        [C]: in function 'require'
        ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:48: in function '_on_insert_enter'
        [string ":lua"]:1: in main chunk_

I installed nvim v0.7.0, and have executed PackerSync.

**Comment by wizard-28** [comment]
Same issue as https://github.com/shaunsingh/nyoom.nvim/issues/6#issuecomment-1047621592

**Comment by shaunsingh** [comment]
Closing in favor of the #6
