### ISSUE TITLE
module 'conjure.eval' not found

### ISSUE THREAD

**Issue by xiaobing-huang** [shaunsingh/nyoom.nvim#14]
Hello Shaunsingh,

Got a new error:

> Error detected while processing /Users/xxxx/.local/share/nvim/site/pack/packer/opt/cmp-conjure/after/plugin/cmp_conjure.lua:
> E5113: Error while calling lua chunk: ...ite/pack/packer/opt/cmp-conjure/lua/cmp_conjure/init.lua:2: module 'conjure.eval' not found:
>         no field package.preload['conjure.eval']
>         no file '/Users/xxxx/.cache/nvim/hotpot//Users/xxxx/.local/share/nvim/site/pack/packer/start/hotpot.nvim/fnl/conjure/eval.lua'
>         no file '/Users/xxxx/.luarocks/share/lua/5.3/conjure/eval.lua'
>         no file '/Users/xxxx/.luarocks/share/lua/5.3/conjure/eval/init.lua'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3.6/luarocks/share/lua/5.3/conjure/eval.lua'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3.6/luarocks/share/lua/5.3/conjure/eval/init.lua'
>         no file '/usr/local/Cellar/luarocks/3.7.0/share/lua/5.3/conjure/eval.lua'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3/luarocks/share/lua/5.3/conjure/eval.lua'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3/luarocks/share/lua/5.3/conjure/eval/init.lua'
>         no file '/usr/local/share/lua/5.3/conjure/eval.lua'
>         no file '/usr/local/share/lua/5.3/conjure/eval/init.lua'
>         no file '/usr/local/lib/lua/5.3/conjure/eval.lua'
>         no file '/usr/local/lib/lua/5.3/conjure/eval/init.lua'
>         no file './conjure/eval.lua'
>         no file './conjure/eval/init.lua'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3/share/lua/5.3/conjure/eval.lua'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3/share/lua/5.3/conjure/eval/init.lua'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3.6/share/lua/5.3/conjure/eval.lua'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3.6/share/lua/5.3/conjure/eval/init.lua'
>         no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/conjure/eval.lua'
>         no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/conjure/eval/init.lua'
>         no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/conjure/eval.lua'
>         no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/conjure/eval/init.lua'
>         no file '/Users/xxxx/.luarocks/lib/lua/5.3/conjure/eval.so'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3.6/luarocks/lib/lua/5.3/conjure/eval.so'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3/luarocks/lib/lua/5.3/conjure/eval.so'
>         no file '/usr/local/lib/lua/5.3/conjure/eval.so'
>         no file '/usr/local/lib/lua/5.3/loadall.so'
>         no file './conjure/eval.so'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3/lib/lua/5.3/conjure/eval.so'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3.6/lib/lua/5.3/conjure/eval.so'
>         no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/conjure/eval.so'
>         no file '/Users/xxxx/.luarocks/lib/lua/5.3/conjure.so'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3.6/luarocks/lib/lua/5.3/conjure.so'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3/luarocks/lib/lua/5.3/conjure.so'
>         no file '/usr/local/lib/lua/5.3/conjure.so'
>         no file '/usr/local/lib/lua/5.3/loadall.so'
>         no file './conjure.so'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3/lib/lua/5.3/conjure.so'
>         no file '/Users/xxxx/.asdf/installs/lua/5.3.6/lib/lua/5.3/conjure.so'
>         no file '/Users/xxxx/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/conjure.so'
> stack traceback:
>         [C]: in function 'require'
>         ...ite/pack/packer/opt/cmp-conjure/lua/cmp_conjure/init.lua:2: in main chunk
>         [C]: in function 'require'
>         ...pack/packer/opt/cmp-conjure/after/plugin/cmp_conjure.lua:1: in main chunk
> Press ENTER or type command to continue

**Comment by shaunsingh** [comment]
oops, cop-conjure should be loaded after cmp obviously.

**Comment by shaunsingh** [comment]
Should be fixed now
