### ISSUE TITLE
Migrate to lazy.nvim

### ISSUE THREAD

**Issue by glyh** [shaunsingh/nyoom.nvim#144]
As per https://github.com/wbthomason/packer.nvim/issues/1229, packer's author moved to lazy, so I guess the project will be dead soon.

**Comment by Suyashtnt** [comment]
> I'm curious, what features it will provides that lazy.nvim can't?

Stupidly fast rollbacks, direct libgit2 intergration (its much faster than the git CLI), and the ability to be used outside of neovim (e.g. direct nix intergration). It's meant to have a similar featureset to lazy but faster and more oxidized (its written in rust)

**Comment by glyh** [comment]
Integration with nix sounds interesting, ever consider integration with guix as well?
