### ISSUE TITLE
Error during install of nyoom, 'keymap' a nil value

### ISSUE THREAD

**Issue by ragdoll2iguess** [shaunsingh/nyoom.nvim#16]
When replacing my old config with the current nyoom, opening nvim results in the following error (before `:PackerCompile` and `:PackerSync` are possible):

>error detected while processing /home/eris/.config/nvim/init.lua:
>E5113: Error while calling lua chunk: >...ot/home/eris/.config/nvim/fnl/conf/modules/core/maps.lua:3: attempt to index field >'keymap' (a nil value)
>stack traceback:
>        ...ot/home/eris/.config/nvim/fnl/conf/modules/core/maps.lua:3: in main chunk
>        [C]: at 0x7f197a9cd7d0
>        [C]: in function 'require'
>        ...che/nvim/hotpot/home/eris/.config/nvim/fnl/conf/init.lua:1: in main chunk
>        [C]: in function 'require'
>        /home/eris/.config/nvim/init.lua:38: in main chunk
>Press ENTER or type command to continue

**Comment by shaunsingh** [comment]
are you using nvim nightly or v0.6? Nyoom requires nightly

**Comment by ragdoll2iguess** [comment]
On my last void install I definitely was. I thought I was on this install, but I might not be. When I get home from work I'll double check.

Hopefully that's the issue.

**Comment by ragdoll2iguess** [comment]
ok turns out I don't have nightly. Compiling that now, going to report back. It should fix everything.

**Comment by ragdoll2iguess** [comment]
ok coolio, everything works correctly now, except an issue with cmp-lsp, but I'll open another issue for that.
