### ISSUE TITLE
Issue with :PackerSync, unable to update hrsh7th/cmp-nvim-lsp

### ISSUE THREAD

**Issue by ragdoll2iguess** [shaunsingh/nyoom.nvim#17]
Upon using :PackerSync, cmp-nvim-lsp fails to update with the following error:

> ✗ Failed to update hrsh7th/cmp-nvim-lsp
  Errors:
    fatal: Not possible to fast-forward, aborting.
    a2f3d16

**Comment by shaunsingh** [comment]
Packer is annoying about certain git features. I recommend just deleting the packer folder (its at `~/.local/share/nvim/site/pack/packer/`) and running `:PackerSync` again. I don't believe its a Nyoom-specific issue,

**Comment by ragdoll2iguess** [comment]
ok, I deleted the packer folder, and on nvim startup received the following error during the automatic packer compilation:

>Error in packer_compiled: /home/eris/.config/nvim/plugin/packer_compiled.lua:299: module 'Comment' not found:^@^Ino field package.preload['Comment']^@^Ino file '/home/eris/.
cache/nvim/hotpot//home/eris/.local/share/nvim/site/pack/packer/start/hotpot.nvim/fnl/Comment.lua'^@^Ino file './Comment.lua'^@^Ino file '/home/eris/neovim/.deps/usr/share/l
uajit-2.1.0-beta3/Comment.lua'^@^Ino file '/usr/local/share/lua/5.1/Comment.lua'^@^Ino file '/usr/local/share/lua/5.1/Comment/init.lua'^@^Ino file '/home/eris/neovim/.deps/u
sr/share/lua/5.1/Comment.lua'^@^Ino file '/home/eris/neovim/.deps/usr/share/lua/5.1/Comment/init.lua'^@^Ino file '/home/eris/.cache/nvim/packer_hererocks/2.1.0-beta3/share/l
ua/5.1/Comment.lua'^@^Ino file '/home/eris/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/Comment/init.lua'^@^Ino file '/home/eris/.cache/nvim/packer_hererocks/2.1.0
-beta3/lib/luarocks/rocks-5.1/Comment.lua'^@^Ino file '/home/eris/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/Comment/init.lua'^@^Ino file './Comment.so'
^@^Ino file '/usr/local/lib/lua/5.1/Comment.so'^@^Ino file '/home/eris/neovim/.deps/usr/lib/lua/5.1/Comment.so'^@^Ino file '/usr/local/lib/lua/5.1/loadall.so'^@^Ino file '/h
ome/eris/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/Comment.so'
Please check your config for correctness

**Comment by ragdoll2iguess** [comment]
So, replacing ~/.../packer/ with the original packer file from before I switched to the current nyoom, but manually deleting only ../nvim-cmp-lsp makes it work, but constantly try and fail to delete the other contents of the packer file on every :PackerSync. Also lsps don't connect to the buffers when they should, but that's probably for another issue -- will only make that once we can figure out this one in case this is what breaks the lsps.

**Comment by ragdoll2iguess** [comment]
Ok, everything works now perfectly on a fresh void install.

**Comment by shaunsingh** [comment]
Feel free to reopen the issue if the error comes up again. I think this should be fixed for now
