### ISSUE TITLE
Default `correlate = true` for hotpot options?

### ISSUE THREAD

**Issue by rktjmp** [shaunsingh/nyoom.nvim#19]
You (or your users) may like having the correlate option enabled, which can make errors that occur in lua, at runtime, more debuggable.

https://fennel-lang.org/api
> correlate: when this is truthy, Fennel attempts to emit Lua where the line numbers match up with the Fennel input code; useful for situation where code that isn’t under your control will print the stack traces.

https://github.com/shaunsingh/nyoom.nvim/blob/c47f3a076b47a7ce4c5fdc99580cde98349ccfc8/init.lua#L35-L37

```lua
require("hotpot").setup({ 
    provide_require_fennel = true, 
    compiler = {
      -- modules table passed directly to fennels compiler
      modules = {
        correlate = true
      }
    }
  }) 
```

It does make the lua *less* readable but generally I find it easier to track issues down. Maybe you will want to at least peek at it, it's not a very advertised Fennel feature.

E: I assume aniseed probably has a similar thing too, or maybe its on by default.

**Comment by shaunsingh** [comment]
Thanks, I'll try out the picante branch as well

**Comment by shaunsingh** [comment]
Added in https://github.com/shaunsingh/nyoom.nvim/commit/bb92c2bbb70b48e1345963395141c9c94d8387bb, thanks!

**Comment by shaunsingh** [comment]
Thanks, fixed in latest commit
