### ISSUE TITLE
opening a folder doesn't open a filemanager to navigate said folder.

### ISSUE THREAD

**Issue by derpyzza** [shaunsingh/nyoom.nvim#20]
instead, it just opens a new file with the same name as the folder

**Comment by shaunsingh** [comment]
Normally this would be handled by netrw but I disable that by default. I guess I should add a file manager plugin by default to replace netrw. Is that an acceptable fix?

**Comment by derpyzza** [comment]
yup, that works, thanks :)

**Comment by shaunsingh** [comment]
Sorry for the long delay. Latest commit adds nvim-tree as a replacement for netrw. It should automatically open if you launch nvim with a directory argument (example below), or you can use <leader>o to launch it manually. Enjoy!

https://user-images.githubusercontent.com/71196912/166156534-5e957b7b-2ac4-4c4e-8208-32277a0cae3e.mov
