### ISSUE TITLE
How to turn on github copilot bindings?

### ISSUE THREAD

**Issue by derpyzza** [shaunsingh/nyoom.nvim#22]
sorry if this is a silly question, but how do you turn on keybindings for github copilot?

**Comment by shaunsingh** [comment]
Copilot is a bit weird right now. I have an update I'll push in a day or two which will fix it with `copilot.lua`. After that copilot will function as a cmp source and hopefully the bindings will be less finicky.

**Comment by shaunsingh** [comment]
https://github.com/shaunsingh/nyoom.nvim/commit/ac692e95d5c4774bc824dbf4c26ff70e14d83129 integrates `copilot.lua` and `nvim-cmp` now. You can use tab/shift-tab to navigate through copilot suggestions as you would with a normal completion source, I hope it fixes the issue. 

<img width="802" alt="image" src="https://user-images.githubusercontent.com/71196912/166073521-cc4b6eeb-1896-41cd-b47f-e6e8b52333e1.png">
