### ISSUE TITLE
Could not find cpm-under-comparator

### ISSUE THREAD

**Issue by ragdoll2iguess** [shaunsingh/nyoom.nvim#25]
After updating to the latest version of nyoom, run into the following error:
packer.nvim: Error running config for nvim-cmp:
> .../home/valencia/projects/nyoom.nvim/fnl/conf/pack/cmp.lua:9: module 'cmp-under-comparator' > not found:could not convert modname to path
>	no field package.preload['cmp-under-comparator']
>	no file './cmp-under-comparator.lua'
>	no file '/home/valencia/neovim/.deps/usr/share/luajit-2.1.0-beta3/cmp-under-comparator.lua'
>	no file '/usr/local/share/lua/5.1/cmp-under-comparator.lua'
>	no file '/usr/local/share/lua/5.1/cmp-under-comparator/init.lua'
>	no file '/home/valencia/neovim/.deps/usr/share/lua/5.1/cmp-under-comparator.lua'
>	no file '/home/valencia/neovim/.deps/usr/share/lua/5.1/cmp-under-comparator/init.lua'
>	no file '/home/valencia/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp-under-comparator.lua'
>	no file '/home/valencia/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp-under-comparator/init.lua'
>	no file '/home/valencia/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp-under-comparator.lua'
>	no file '/home/valencia/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/cmp-under-comparator/init.lua'
>	no file './cmp-under-comparator.so'
>	no file '/usr/local/lib/lua/5.1/cmp-under-comparator.so'
>	no file '/home/valencia/neovim/.deps/usr/lib/lua/5.1/cmp-under-comparator.so'
>	no file '/usr/local/lib/lua/5.1/loadall.so'
>	no file '/home/valencia/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/cmp-under-comparator.so'

**Comment by shaunsingh** [comment]
Sorry for the delay, I was rewriting some stuff. Could you check if its fixed now?

**Comment by ragdoll2iguess** [comment]
checking now

**Comment by ragdoll2iguess** [comment]
Ok cool, everything works. Changed some stuff up to fit with the personal changes I made on my fork, for Vimtex and my colorscheme as usual.

Everything from your end works properly now~
