### ISSUE TITLE
Error with NEORG

### ISSUE THREAD

**Issue by ragdoll2iguess** [shaunsingh/nyoom.nvim#26]
When opening .neorg files, the following error appears:
 > packer.nvim: Error running config for neorg: ...ocal/share/nvim/site/pack/packer/opt/neorg/lua/neorg.lua:113: attempt to call field 'nvim_exec_autocmds' (a nil value)

This does not appear to break to break anything though, the neorg appears to load correcly.

**Comment by shaunsingh** [comment]
I think this should be fixed now
