### ISSUE TITLE
Config correctness on fresh install of nyoom

### ISSUE THREAD

**Issue by ragdoll2iguess** [shaunsingh/nyoom.nvim#29]
Fresh install of nyoom, including completely deleting my ~/.local/../pack/ directory and letting everything reinstall fresh yielded the following error on startup:

>Error in packer_compiled: ...ite/pack/packer/start/matchparen.nvim/lua/matchparen.lua:114: >attempt to call field 'create_user_command' (a nil value)
>Please check your config for correctness
>Error detected while processing VimEnter Autocommands for "*":
>Error executing lua callback: .../home/valencia/projects/nyoom.nvim/fnl/parinfer/init.lua:297: >attempt to call field 'nvim_create_user_command' (a nil value)
>stack traceback:
>        .../home/valencia/projects/nyoom.nvim/fnl/parinfer/init.lua:297: in function >'parinfer_command_21'
>        .../home/valencia/projects/nyoom.nvim/fnl/parinfer/init.lua:299: in main chunk
>        [C]: in function 'require'
>        .../home/valencia/projects/nyoom.nvim/fnl/pack/parinfer.lua:4: in function '__index'
>        .../home/valencia/projects/nyoom.nvim/fnl/pack/parinfer.lua:12: in main chunk
>        [C]: at 0x55d98ff66c40

atm it's past midnight, gonna get to bed. Tomorrow I'll see about tinkering, but you might have better luck~

**Comment by shaunsingh** [comment]
> Error executing lua callback: .../home/valencia/projects/nyoom.nvim/fnl/parinfer/init.lua:297: >attempt to call field 'nvim_create_user_command' (a nil value)

Have you recently updated neovim/installed 0.7? My guess is you're missing `nvim_create_user_command` which is fairly new (https://gpanders.com/blog/whats-new-in-neovim-0-7#lua-everywhere)

**Comment by ragdoll2iguess** [comment]
o fuc, that's almost undoubtedly it. Yeah, this is probably user error on my part. I'll update nvim in the morning and let you know if that fixes things.

**Comment by ragdoll2iguess** [comment]
Ok everything works properly. tho with the loss of lsp-installer I just need to muddle through installing the texlap language server.

**Comment by shaunsingh** [comment]
Sorry about that, I removed lsp-installer because the way I set it up became deprecate, I forgot to add it back. 

I'll have lsp-installer up and working again by the end of today

**Comment by ragdoll2iguess** [comment]
radical, thank you. Other than that, everything works perfectly

**Comment by ragdoll2iguess** [comment]
adding lsp-installer back in and just manually setting up lsp-servers seems to work fine and does not seem to add to the startup time as far as I can tell

**Comment by shaunsingh** [comment]
Added lap-installer in the latest commit
