### ISSUE TITLE
set! sets only one option, but is used to set more

### ISSUE THREAD

**Issue by shofel** [shaunsingh/nyoom.nvim#30]
Hey! Thanks for your work on this project :)

I happily fiddle with it a couple of days, ahd besides porting my old config, also focused on simplifying things:
- manage keymaps
- manage plugins
- setting vim options
- migrating from macros to functions where possible

Here is my thoughts on setting vim options macro

## A problem

It sets [only one](https://github.com/shaunsingh/nyoom.nvim/blob/4da176d0afc354e71222522ae4bf110f191ba307/fnl/macros/option-macros.fnl#L14) option
Pretends [to set a list](https://github.com/shaunsingh/nyoom.nvim/blob/4da176d0afc354e71222522ae4bf110f191ba307/fnl/core/defs.fnl#L55)
 of options
Only the first option is really set

### Arity of the function is not checked
It receives two args, but we pass more, and it does not imply an error. This should be because of it's a macro, but not a normal lambda.

By the way, there is not a lot of profit of using macro here. We use a symbol as a first argument, but not a string. BTW, using :keyword or a "keyword" as a first arg is closer to what actually happens in the underlying lua api. Which is considered a good thing according to doom motto :)

I came up with very thin utility function, and removed macros.option-macros to get rid of complexity it introduces 🤔 

## The naming for set!

What does this function do? It sets a vim option. So ı thnk `set-opt!` is a proper name here. As for me, set! is too generic and vague here.

Here is a [thin wrapper](https://github.com/shofel/nyoom.nvim/blob/831f1061b5b53bd07cc4bf662f7702bce89f8728/fnl/utils/options.fnl) fn, I came up with
And here is how [it looks like](https://github.com/shofel/nyoom.nvim/blob/831f1061b5b53bd07cc4bf662f7702bce89f8728/fnl/core/options.fnl)

## vim-set
`vim-set` can be another good name. Yes, without a bang, because bang in lisps usually means side-effect is performed. "set something in vim" is obviously a side effect, and does not require another marker.

An interface could be like this:
``` fennel
(vim-set :g :mapleader " "
            :maplocalleader ",")
```

``` fennel
(vim-set :opt :splitright true
              :splitbelow true)
```

**Comment by shaunsingh** [comment]
Thank for the input. I was actually thinking of making the set/let macros *more* complicated, to further match vimscript (e.g. `(set! nowrap)` expands properly into (set wrap false). While I like your implementation, I'm not the biggest fan of doing global variables and options within the same macro, even if its closer to bare bones

I'll draft up the implementation I'm thinking of in my head, and I think a good compromise is to include both macros. Users can opt in for more syntastical sugar if they please but also opt for a more bare-bones experience if they choose to. Would that work for you?

As for the naming, I tried to make the macros similar to what you would fine configuring emacs (hence the name of `use-package!` as well). Usually that wold be `setq`, `q` being for quotes but I felt that it wasn't nessecary, hence the name of `(set! ...)`. I agree set-opt! would be a better name.

**Comment by shofel** [comment]
Yep, thanks for your attention.

BTW, as for me, there is more sense to stay closer to nvim syntax and semantics, than to those of emacs or vimscript :)

**Comment by shofel** [comment]
So, now it should fixed by [commit](https://github.com/shaunsingh/nyoom.nvim/commit/9470f876ae0aa91491a0ffb0818afe79412d71a2), right?

By the way, you give name `aux` for functions, which do "a step of recursion". Is it a common practice or an ad-hoc decision? I believe a better name for those fns is `recur` or `step`

**Comment by shaunsingh** [comment]
> So, now it should fixed by [commit](https://github.com/shaunsingh/nyoom.nvim/commit/9470f876ae0aa91491a0ffb0818afe79412d71a2), right?

Yup, you can use `set-multi!`. `Aux` is an ad-hoc decision,
