### ISSUE TITLE
Packer: problems and proposals

### ISSUE THREAD

**Issue by shofel** [shaunsingh/nyoom.nvim#32]
When dealing with `use-package!` macro I faced two troubles.

1. It's unsafe to re-evaluate the buffer with package declarations
Packages are duplicated in _G.pkgs list. The fastest solution is to reset the list after calling `packer.startup`

2. naming of custom keys is confusing:
- `config!` is for loading a config from file. A better name is `load-file`. Or `config-file`?
- `init!` to call the `setup` function. A better name is `call-setup`

For the second I extracted two macros to call them explicitly
``` fnl
(macro call-setup [name config]
  "To config a plugin: call the setup function."
  `(λ []
      ((. (require ,name) :setup)
       ,config)))

(macro load-file [name]
  "To config a plugin: load a file from pack/ folder."
  `#(require ,(.. "pack." name)))
```

They are to be used like this
``` fnl
   (pack :neovim/nvim-lspconfig
         {:config (load-file "lsp")
          :requires [(pack :j-hui/fidget.nvim {:after :nvim-lspconfig
                                               :config (call-setup :fidget)})]})
```

**Comment by shofel** [comment]
Also I tried to come up with some aesthetically appealing interface.  
it's definitely sad that packer uses mixed tables as package specs :D

### More data, less calls
I thought about a macro which converts to mixed table implicitly:
``` fnl
(use-plugins
  [[:wbthomason/packer.nvim]
   [:ggandor/lightspeed.nvim {:config (load-file "lightspeed")}]])
```
But it needs an extra work of handling `:requires` recursively. Doesn't look too difficult, but I didn't succeeded :)

### Use and pack
decouple `use` and `pack`: pack explicitly, but then send to a function which calls `use` on each plugin
``` fnl
(local plugins
  [(pack :wbthomason/packer.nvim)
   ;; Set and document keymaps
   (pack :folke/which-key.nvim {:config (call-setup :which-key)})
   (pack :lewis6991/gitsigns.nvim {:config (call-setup :gitsigns)
                                   :requires [(pack :nvim-lua/plenary.nvim)]})])

;; Call `startup` with prepaired callback.
(packer.startup (lambda [use]
                  (each [_ x (pairs plugins)]
                    (use x))))
```
As a bonus, the top-level plugins (e.g. gitsigns) are marked exactly the same way as requirements (e.g. plenary)

**Comment by shofel** [comment]
Feel free closing the issues, because a discussion in a closed issue is not worse than a in an open one

**Comment by shaunsingh** [comment]
Thanks for the comments. I love the work you've been doing on the packer macros over on your branch, a few thoughts: 

1. I agree with the idea of changing the pkgs global variable to local and safer. The original reasoning behind making it a global variable was that you could call `use-package!` from *any* file and use it to both install and configure your plugins. This was supposed to be combined with a module system which never came to fruition. 
2. `call-setup` and `load-file` both look great. I agree that its probably a good idea to part out those two macros as you did
3. I'm not *as* big a fan of changing the packer syntax into something different. The `use-package!` macro is supposed to mimic the emacs package manager of the same name, and as nyoom is supposed to *slightly lean* into being a config for emacs refugees I feel like we should keep the current syntax.

**Comment by shaunsingh** [comment]
added 1. and 2. in the recent commit.

**Comment by shofel** [comment]
Yeah, when reading the code, I did get the idea behind making the `pkg` global. I like the idea of modular config. But the nature of packer (and probably the others plugin managers for nvim) is against it. I mean, all the plugins are installed at once, with a single call of `packer.startup`.

There could have been existing a more dynamic package manager. I mean, instead of the only function call, which does everything, it could be a lot of calls, each to install a package or do another separate piece of job.

Maybe it's even possible with `custom installers` of packer.

**Comment by shofel** [comment]
Thanks for using my humble macros :)

**Comment by shaunsingh** [comment]
No problem, the honor is all mine : )
