### ISSUE TITLE
Broken `<Tab>` -- macOS Monterey, iTerm2

### ISSUE THREAD

**Issue by mjachi** [shaunsingh/nyoom.nvim#48]
I can only get a single use out of `TAB` with each run of `nvim`, after which my `TAB` key just feeds in `^I`. This seems particular to something in `nyoom`, but I cannot find it -- hopefully someone else knows more about this I do? To be clear: run `nvim`, do anything, hit `TAB` once in search of a completion, functions as expected the first time; hit `TAB` at any point again, and `^I` is received instead. Then, exiting and restarting `nvim` "resets" something, and I get another use of `TAB`

For the sake of reproducibility, I am on vanilla `nyoom` as of the most recent commit on `main`; the only difference is the addition of a few simplified keybinds, none of which deal with `TAB`. This was an issue before their addition, and I've naturally been hesitant to dive much further til I figure out what's doing this.

`vim` etc perform just fine with `TAB`, so that seems to at least eliminate some strange interaction between HHKB, iTerm2, and whatever ends up actually being fed in.

**Comment by mjachi** [comment]
Can constrain the issue... it isn't the first press of `TAB`, but instead seems to be the first time that the completion window closes, where it refuses to open back up. This issue with the window opening is particular to normal mode; in insert mode, the window will still open, but `TAB` does not function as expected.

**Comment by mjachi** [comment]
Threw in the towel on fennel, sadly... can't have the time to spend on this. Currently porting the setup into Lua + what I've used in the past (also written in Lua). Will follow up if I run into this again/ a solution to this at some point. Mixing brand new language with API's I'm barely familiar with is too much.

I'm fairly convinced that this is particular to something in this setup, but I should admit that this is coming onto a fresh macOS install (after judging several package managers to be destroyed beyond easy repair in addition to having many a package I simply didn't need, starting fresh is my go-to) and I _know_ that between my keyboard, macOS, and iTerm2, one can find some very interesting interactions.

**Comment by shaunsingh** [comment]
Sorry I didn't reply earlier, I haven't looked into it but I assume its caused by the snippets plugin + cmp, I'll definitely take look soon and push a fix. That being said, you can definitely take a look at datwaft's config

**Comment by mjachi** [comment]
Will check out datwaft's... thanks for the rec.

If you're able to figure out, would certainly save me a lot of time from reimplementing/ so much of this haha... I might just finish out a port regardless, since it may be easier for me to maintain in the long run. Thanks in advance!

**Comment by Icy-Thought** [comment]
> If you're able to figure out, would certainly save me a lot of time from reimplementing/ so much of this haha...

Checkout the PR I just submitted and tell me if it solves your issue. :smile:

**Comment by shaunsingh** [comment]
Merged, thank you :)

**Comment by Icy-Thought** [comment]
Glad to help out! :)

**Comment by mjachi** [comment]
Sorry, been a bit but am back on this. To be frank, I do not see what has materially changed with this. This seems to have eliminated it before I enter insert mode; but, after I enter insert mode, do whatever, and exit (ie, exit insert mode), it remains broken. Could it be something with lazy-loading? I am not confident on my understanding of how you put that together @shaunsingh

**Comment by Icy-Thought** [comment]
What do you mean by `before entering insert mode` and `remains broken`?

Do show a short clip about what you had before vs what you have now if you have the ability to do so. (assuming you still have your lua config laying around somewhere)

Also, the expected behaviour for the current `nvim-cmp` config is to display completions after writing/updating your input and later select the completions through <kbd>Tab</kbd> and <kbd>Shift Tab</kbd> to select previous completions. And when the cursor is placed affront of the word, it would insert a tab.

**Comment by shaunsingh** [comment]
The default behavior, as @Icy-Thought mentioned is to act as a normal tab if a completion menu isn't shown. If a completion menu is available, then it cycles through the completion menu. Note that nyoom determines indenting through `nvim-treesitter`, but I don't think thats what causes the issue, as you said it only occurs when you enter insert mode and leave

I'm not exactly sure whats the issue you're experiencing, but it's definitely "caused" by nvim-cmp, as we lazy-load nvim-cmp and its completion tools on insert-mode. Personally, I think the current behavior is whats expected for most people coming from emacs' company-mode (personally I don't use tab much either, I always use `C-n` and `C-p`). That being said, if its "unexpected behavior" I'll be more than glad to change the defaults. 

Current behavior:

https://user-images.githubusercontent.com/71196912/183551745-13b6ce4e-1ad6-43fa-9109-3bee72d6ba16.mov

If you don't mind not being able to use `tab` to cycle through cmp completions, then feel free to delete these lines from `cmp.fnl` and your issue should be rectified: 

https://github.com/shaunsingh/nyoom.nvim/blob/a4dffed61bac88a3b3aea93ff3b627d7e64a2e5d/fnl/pack/cmp.fnl#L72-L88

**Comment by mjachi** [comment]
`before entering insert mode` (like, right when I open neovim) and `remains broken` (the same thing I saw before your PR) will be clear with the video. Probably should have uploaded one sooner. Hopefully it's very clear. I can reset to my Lua config but I don't think there's much to be gained... its TLDR this does not work as intended versus I could always hit `TAB` and be met with a completion window. I'm aware of the expected behavior... I've used this for a while now. Having your commandline filled with `^I` and no suggestions is certainly not expected.

https://youtu.be/0Mj_nQZbKUc

**Comment by mjachi** [comment]
> The default behavior, as @Icy-Thought mentioned is to act as a normal tab if a completion menu isn't shown. If a completion menu is available, then it cycles through the completion menu. Note that nyoom determines indenting through `nvim-treesitter`, but I don't think thats what causes the issue, as you said it only occurs when you enter insert mode and leave
> 
> I'm not exactly sure whats the issue you're experiencing, but it's definitely "caused" by nvim-cmp, as we lazy-load nvim-cmp and its completion tools on insert-mode. Personally, I think the current behavior is whats expected for most people coming from emacs' company-mode (personally I don't use tab much either, I always use `C-n` and `C-p`). That being said, if its "unexpected behavior" I'll be more than glad to change the defaults.
> 
> Current behavior:
> 
>  Untitled.mov 
> If you don't mind not being able to use `tab` to cycle through cmp completions, then feel free to delete these lines from `cmp.fnl` and your issue should be rectified:
> 
> https://github.com/shaunsingh/nyoom.nvim/blob/a4dffed61bac88a3b3aea93ff3b627d7e64a2e5d/fnl/pack/cmp.fnl#L72-L88

How are you able to upload videos in the comment?

**Comment by shaunsingh** [comment]
Ah, I understand the issue now. Would integrating https://github.com/hrsh7th/cmp-cmdline be a viable solution?

**Comment by Icy-Thought** [comment]
Your earlier comment sure made it confusing af. You want completions for the command-line, yes? 

I personally use `wilder.nvim`, but you can always resort to `cmp-cmdline` as shaunsingh had suggested.

**Comment by mjachi** [comment]
Sorry, I should have uploaded that video a long, long time ago. Honestly with the first post.

I tried doing that quickly before opening the issue to begin with, but it was fruitless. As I understand it, that plugin is just adding the source? I am of the opinion that this is in the neighborhood of "something is not being reloaded once I exit `insert` mode." There is a nontrivial chance that I just didn't plug it in correctly, so maybe it's worth the second shot.

**Comment by Icy-Thought** [comment]
It appears like you had `cmp-cmdline` setup earlier: https://github.com/mjachi/neovim_setup/blob/3fee9190d9b1817aaf3bc787f87123024de7c364/lua/core/plugins.lua#L79

**Comment by mjachi** [comment]
> It appears like you had `cmp-cmdline` setup earlier: https://github.com/mjachi/neovim_setup/blob/3fee9190d9b1817aaf3bc787f87123024de7c364/lua/core/plugins.lua#L79

Yeah I had it in the old one. I consider shaun to be a, shall we say, neovim wizard, so I did notice it missing, but I just don't know fennel. Addt. the vid shows it working without that added in at the beginning exactly how it worked on my old config that you pulled up _with_ `cmp-cmdline`, but just not after I exit `insert` mode as we've been discussing.

I guess what I mean is that... even without `cmp-cmdline`, ie, pure, out of the box `nyoom` as of your PR getting merged, it seemed to be what I was looking for besides it breaking as soon as I actually used the text editor as a text editor.

Man.... I just want to be able to hit `Tab` after `:vsp ` and see the files in my CWD haha... that's probably 60% of what I use it for.

**Comment by Icy-Thought** [comment]
If not fixed by tomorrow I'll try to push a PR. Have other work that I got to hand in soon.. :/

**Comment by mjachi** [comment]
Are either of you able to recreate this?

**Comment by Icy-Thought** [comment]
Just uninstalled `wilder.nvim` and completion seems to be working fine.. I wonder what is breaking your command-line completions.

**Comment by mjachi** [comment]
Even following the same sequence from the second half of the clip? I've reinstalled `nyoom` like 3 times so I'm certain something didn't bug out in the build, though _maybe_ there's something weird with macOS in the build system... Really like the base setup + options, but this is very frustrating...

**Comment by Icy-Thought** [comment]
@mjachi for now, you can resolve to the following:

Add to `pack/pack.fnl`:
```fennel
(use-package! :gelguy/wilder.nvim
              {:run :UpdateRemotePlugins
               :event :CmdlineEnter
               :requires [(pack :romgrk/fzy-lua-native)]
               :config (load-file wilder)})
```

Config: https://github.com/Icy-Thought/nvim.d/blob/main/ereshkigal/fnl/plugins/ui/wilder.fnl <- add file to `pack/`

**Comment by shaunsingh** [comment]
> I tried doing that quickly before opening the issue to begin with, but it was fruitless. As I understand it, that plugin is just adding the source? I am of the opinion that this is in the neighborhood of "something is not being reloaded once I exit insert mode." There is a nontrivial chance that I just didn't plug it in correctly, so maybe it's worth the second shot.

I'm of the same opinion, that between the first time you open the command line and the second time (after entering insert mode) your experience should be the same. To resolve this, I'll load `nvim-cmp` on either whenever you enter insert mode, or command line mode, whichever comes first. 

> I personally use wilder.nvim, but you can always resort to cmp-cmdline as shaunsingh had suggested.

Personally I prefer adding `cmp-cmdline` rather than `wilder.nvim` support solely because I feel wilder.nvim recreates a large part of what cmp does, and I'd rather extend `nvim-cmp` rather than have to support an extra plugin. 

> Man.... I just want to be able to hit Tab after :vsp and see the files in my CWD haha... that's probably 60% of what I use it for.

I believe this should solve your issue, 

> Are either of you able to recreate this?

Yup, I can recreate the issue. Thanks for notifying me of it, I generally start typing as soon as I start neovim and don't use the command line all too often. 

TDLR: 
- I'll load cmp when you enter the command line for the first time as well, so the default wildmenu will be removed right away
- I'll add `cmp-cmdline` as a replacement for the default wildmenu, so your `:vsp` completion should work wonderfully

It might be a while since I add the changes since I'm working on moving over nyoom to a module structure (where you can enable/disable groups of packages similar to that of doomemacs). I'll be sure to fix it soon though

Hope that helps :)

**Comment by shaunsingh** [comment]
> Even following the same sequence from the second half of the clip? I've reinstalled nyoom like 3 times so I'm certain something didn't bug out in the build, though maybe there's something weird with macOS in the build system... Really like the base setup + options, but this is very frustrating...

Yeah, the getting up-and-started experience is also something I need to work on, as well as teaching users both how nyoom works as well as how to extend it. Along with that modularization I'm working on improving the documentation (written in neorg!), so users will know exactly what works, how it works, why it works, and what macros it uses, rather than having to "learn by example" and scrub through the source code

**Comment by Icy-Thought** [comment]
Alright, here is a working solution:

Add to `pack/pack.fnl`:
```fennel
(use-package! :hrsh7th/nvim-cmp
                        {:event :VimEnter ;; to work on vim-enter
 :requires  [ ;; ... append to requires
                                           (pack :hrsh7th/cmp-cmdline {:after :nvim-cmp})]
                                           ;; ...

```

Add the following to `pack/cmp.fnl`
```fennel
(setup.cmdline "/" {:mapping (mapping.preset.cmdline)
                    :sources [{:name :buffer}]})

(setup.cmdline ":" {:mapping (mapping.preset.cmdline)
                    :sources (sources [{:name :path}
                                       {:name :cmdline}])})
```

I'll eventually push this as a PR if not done by someone else!

**Comment by mjachi** [comment]
Alright, it indeed seems to have been that it was missing `cmp-cmdline`... thanks for all your continued efforts @shaunsingh and for you help @Icy-Thought
