### ISSUE TITLE
clean Installation doesn't work

### ISSUE THREAD

**Issue by luxus** [shaunsingh/nyoom.nvim#54]
````sh 
->> cd ;rm -rf ~/.config/nvim ~/.local/share/nvim/
->> git clone --depth 1 https://github.com/shaunsingh/nyoom.nvim.git ~/.config/nvim; cd ~/.config/nvim
->> bin/nyoom install
Installing Required Plugins
->> bin/nyoom sync
NVIM v0.8.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by _nixbld1
error: -n requires an argument
running: nyoom sync on version

E5113: Error while calling lua chunk: Vim:E185: Cannot find color scheme 'oxocarbon'
stack traceback:
        [C]: at 0x010446474c
        [C]: in function 'require'
        ...e/nvim/hotpot/Users/luxus/.config/nvim/fnl/core/init.lua:16: in main chunk
        [C]: in function 'require'
        /Users/luxus/.config/nvim/init.lua:2: in main chunk
Loading Packer
Compiling Module
Initiating Packer
Loading User Plugins

````

**Comment by luxus** [comment]
mhh never mind... after restarting the shell it works :D

**Comment by shaunsingh** [comment]
The make tasks were a stop-gap while I was working out the modules system and the nyoom-cli. Now you can just run 
`nyoom install` and `nyoom sync`, and when you open up neovim it should be ready to go!

**Comment by luxus** [comment]
i just want to ask how long until your module system :D

**Comment by luxus** [comment]
i updated the first post.

**Comment by shaunsingh** [comment]
> error: -n requires an argument

Just pushed a fix for that 

```
E5113: Error while calling lua chunk: Vim:E185: Cannot find color scheme 'oxocarbon'
stack traceback:
        [C]: at 0x010446474c
        [C]: in function 'require'
        ...e/nvim/hotpot/Users/luxus/.config/nvim/fnl/core/init.lua:16: in main chunk
        [C]: in function 'require'
        /Users/luxus/.config/nvim/init.lua:2: in main chunk
```

Whats happening here is that 
1. nyoom tries to load the builtin theme and fails 
2. theme installs 
3. nyoom should work just fine

I'll bootstrap the theme with nyoom so this error doesn't occur in the future

**Comment by luxus** [comment]
perfect. great work.. quickest fix :D
looking forward to future development.
did you integrate it in your flake?

**Comment by shaunsingh** [comment]
Colorscheme should be bootstrapped with `nyoom install` now as well, so the error doesn't occur 
I think in the future I'll move the colorscheme back to fennel to make install simpler and remove the extra rust dependency

> did you integrate it in your flake?
With the flake I wanted to integrate it with `nyoom sync` so the packages are handled through nix and properly pinned instead `flake.lock`. Thats coming soon, for now the flake option became broken so I removed it altogether

**Comment by luxus** [comment]
i saw the hate you got for the rust thing :(
i like the theme and i think removing the rust dep. will help adoption.
have you did a how much different colors does it use? it is possible to make a base16 theme for some rice? :D

**Comment by luxus** [comment]
<img width="275" alt="Screenshot 2022-08-17 at 01 59 27" src="https://user-images.githubusercontent.com/7449/185005296-f486f80a-592a-41b6-a005-3292034ed769.png">
looks a little off
btw i wrote you in discord :D

**Comment by shaunsingh** [comment]
> i saw the hate you got for the rust thing :(
> i like the theme and i think removing the rust dep. will help adoption.
> have you did a how much different colors does it use? it is possible to make a base16 or 17 theme for some rice? :D

It wasn't really any hate its just I did it as a fun experiment of sorts of writing neovim plugins in rust, and it doesn't *need* to be in rust for any reason. Probably would be a good thing to port it back and make the config more accessible

The scheme is has 18 colors: 
The first 16 follow the base16 format 
the 17th color is a "blend" color for contrast
the 18th color is a "blank" color for transparent items 

My own dotfiles use this colorscheme in base16 format: https://github.com/shaunsingh/nix-darwin-dotfiles/blob/main/modules/themes/base16-carbon-dark.yaml, if it helps.
