### ISSUE TITLE
handling additional addons and configurations

### ISSUE THREAD

**Issue by luxus** [shaunsingh/nyoom.nvim#62]
it would be great if additional addons don't prevent from updating from master.
it would be nice if there is a place where i can overwrite the theme/addon configs without having a pull conflict. 

any plans how to add common addons? maybe a .md where people can PR addons? with instructions where to add code?

**Comment by shaunsingh** [comment]
common addons as in? once the module system is finalized I'll make official contributing guidelines but for now: 
1. New modules / PR to modules can just be PR'd as you would with any other project
2. "Contrib modules" (modules that are great but outside the scope of nyoom) can be uploaded to their own repository. I'll make a `contrib` folder, and these contribute modules will be git submodules in that contrib folder
3. User configuration (stuff that doesn't fall under the "improved defaults" umbrella) should stay between `config.fnl` and `packages.fnl`. Currently this is a bit hard, but in the future you'll be able to change module defaults within `config.fnl`

I hope that makes sense

**Comment by luxus** [comment]
2. is what i mean with common, modules that are out of scope. the contrib idea sounds good 
3. how about a user/config.fnl that get loaded last and could overwrite stuff like core modules settings, colorschemes and keybindings

imho users should be able to update /.config/nvim with a git pull and still be able to access to the user config and the contrib modules

**Comment by shaunsingh** [comment]
re number 2, yeah thats the idea once all the core stuff is sorted. I want to make the module system final or else people who make modules will have to remake them with new changes etc. 

As for number 3, thats the intention of the current `config.fnl` and `packages.fnl`. It's supposed to be entirely for use configuration and packages. Its just I haven't gotten around to making the functions/macros for it, as I've been focusing on the aforementioned module system (and recently the colorscheme rewrites)

**Comment by luxus** [comment]
thanks,
i added some stuff to my config
https://github.com/luxus/nyoom.nvim/tree/develop
its mostly straight forward

**Comment by shaunsingh** [comment]
basic support for `after` has been added, along with additional modules etc. Closing this issue for now
