### ISSUE TITLE
`modeline` doesn't show the diagnostic numbers properly

### ISSUE THREAD

**Issue by smb374** [shaunsingh/nyoom.nvim#65]
As the following screenshot shows, the lsp diagnostics showing warnings & errors are not working properly:
![diagnostic](https://user-images.githubusercontent.com/13521730/187075600-4c4cb9aa-b0f9-4dd7-9f95-bdddbb6af9df.png)
And running `:lua print(vim.diagnostic.severity.WARN)` shows the correct number:
![echo_result](https://user-images.githubusercontent.com/13521730/187075662-d83ac690-c4d1-40c6-a019-5c43e5258d6f.png)

It seems like that particular section isn't being updated properly, as other section works normally.

**Comment by shaunsingh** [comment]
ah, seems like the Modeline isn't concatenating the errors/warnings properly, I'll seperate everything and make it more clear

**Comment by smb374** [comment]
It seems like that I misunderstood the meaning of `vim.diagnostic.severity.WARN`.

After some time of researching, I've managed to make it working with the following changes:
```fennel
;; get the number of entries of certain severity
(fn get-severity [s]
  (length (vim.diagnostic.get 0 {:severity s})))

(nyoom-module-p! lsp
  (fn get-lsp-diagnostic []
    (when (not (rawget vim :lsp))
      (lua "return \"\""))
    ;; (local count [0 0 0 0])
    ;; (local result {:errors (. count vim.diagnostic.severity.ERROR)
    ;;                :warnings (. count vim.diagnostic.severity.WARN)
    ;;                :info (. count vim.diagnostic.severity.INFO)
    ;;                :hints (. count vim.diagnostic.severity.HINT)})
    ;; replaced with `get-severity`, this will make the numbers updated when saved or syntax error.
    (local result {:errors (get-severity vim.diagnostic.severity.ERROR)
                   :warnings (get-severity vim.diagnostic.severity.WARN)
                   :info (get-severity vim.diagnostic.severity.INFO)
                   :hints (get-severity vim.diagnostic.severity.HINT)})
    (string.format " %%#StatusLineDiagnosticWarn#%s %%#StatusLineDiagnosticError#%s "
                   (or (. result :warnings) 0) (or (. result :errors) 0))))

```

Reference: [`:h vim.diagnostic.get()`](https://neovim.io/doc/user/diagnostic.html)

**Comment by shaunsingh** [comment]
Should be fixed now
