### ISSUE TITLE
Hi how to install using pakcer?

### ISSUE THREAD

**Issue by jinfagang** [shaunsingh/nyoom.nvim#69]

**Comment by thezaff** [comment]
https://github.com/shaunsingh/nyoom.nvim/blob/main/docs/modules.md

**Comment by thezaff** [comment]
>  I am rewriting parts of the modules structure so It might see a few breaking changes soon

Do you think it will be useless to set up new modules right now, if you are going to bring some breaking changes soon?

**Comment by shaunsingh** [comment]
They won't be big breaking changes, so feel free to create modules. For PR's to nyoom, I'll just quickly update them myself. For personal modules I'll add a small doc explaining the changes
