### ISSUE TITLE
Error just after new (successful) install and starting nyoom for the first time.

### ISSUE THREAD

**Issue by coder1044324** [shaunsingh/nyoom.nvim#71]
After starting for the first time, nyoom was installing tree-sitter parsers. Mid way, I encountered this error.

```
Treesitter parser for markdown_inline has been installed                                                                                  
Error detected while processing BufReadPost Autocommands for "*":                                                                         
Error executing lua callback: ...ar/neovim/HEAD-711ef4e_1/share/nvim/runtime/filetype.lua:20: Vim(lua):E5108: Error executing lua ...vim/s
ite/pack/packer/opt/packer.nvim/lua/packer/load.lua:171: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/pac
ker/opt/packer.nvim/lua/packer/load.lua:142: Vim(source):E5113: Error while calling lua chunk: ...pack/packer/opt/cmp-conjure/after/plugin
/cmp_conjure.lua:1: module 'cmp' not found:                                                                                               
stack traceback:                                                                                                                          
        [C]: in function 'cmd'                                                                                                            
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:171: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/l
oad.lua:167>                                                                                                                              
        [string ":lua"]:1: in main chunk                                                                                                  
        [C]: in function 'nvim_buf_set_option'                                                                                            
        ...ar/neovim/HEAD-711ef4e_1/share/nvim/runtime/filetype.lua:20: in function <...ar/neovim/HEAD-711ef4e_1/share/nvim/runtime/filety
pe.lua:11>                                                                                                                                
stack traceback:                                                                                                                          
        [C]: in function 'nvim_buf_set_option'                                                                                            
        ...ar/neovim/HEAD-711ef4e_1/share/nvim/runtime/filetype.lua:20: in function <...ar/neovim/HEAD-711ef4e_1/share/nvim/runtime/filety
pe.lua:11> 
```

Any insights/suggestions for a fix?
Potentially useful info:
running macOS Monterey, with M1 pro
nyoom version c58b0df
NVIM v0.8.0-dev-758-g711ef4eac

Note that I then entered out of it and nyoom itself is functional as an editor. If I open lua files there's another error (which could be related):
```
Spawning language server with cmd: `lua-language-server` failed. The language server is either not installed, missing from PATH, or not executable.
```
No errors when opening fennel files.
Also, not sure if this link has any helpful stuff? [link](https://stackoverflow.com/questions/45416839/error-detected-while-processing-bufread-auto-commands-for-py)

Thanks in advance!

**Comment by shaunsingh** [comment]
I just pushed an update, I think this should fix the first issue. 

> Spawning language server with cmd: `lua-language-server` failed. The language server is either not installed, missing from PATH, or not executable.

You can run `:Mason` to automatically install language servers and tooling for enable modules, assuming you've enabled the `mason` module as well

**Comment by coder1044324** [comment]
Just did a fresh reinstall and got the exact same error after opening a file (when it was installing tree-sitter parsers).
Also ran Mason and it installed 16 packages, but then whenever I reopen the file and run :Mason it ends up reinstalling the same stuff for some reason?

**Comment by shaunsingh** [comment]
Could you kindly run `nvim --version` for me, I think the error is being thrown because `vim.cmd` isn't available which is a fairly new (v0.8) feature, I might be wrong though

> run :Mason it ends up reinstalling the same stuff for some reason?

I'll update the documentation with more info but you're only supposed to run it once

How I configured mason is because the language modules are defined standalone, `Nyoom` merely hooks into mason to install the binaries themselves. After that mason isn't touched again, and the binaries are added to vim's search path. It's a bit hacky but IMO aligns the best with how Nyoom functions internally. 

What I'll probably do is have a script that quickly checks if the required servers have been installed at Nyoom's start, and run  `:Maso` if they haven't, and to the user the `:Mason` command will be unavailable and return an error the same way `:PackerSync` currently does 

Ideally I'd like to define things declaratively rather than have the user of the config imperatively install language servers/parsers/linters/etc.

**Comment by coder1044324** [comment]
```
NVIM v0.8.0-dev-758-g711ef4eac
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by ___@___s-MBP-2

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-711ef4e_1/share/nvim"

Run :checkhealth for more info
```
^^^ is the output from running `nvim --version`. It seems to be v0.8.

That makes sense; don't yet know too much about how exactly nyoom works, but I'll be working on my understanding of it soon.

**Comment by demiancodes** [comment]
Is it a development version? I had a very similar issue to you. I installed Astro Vim thinking that nyoom was broken for macOs. But it also broke. So I installed a stable release of NeoVim and it worked. I am going to try and install nyoom later today on this current stable version.

**Comment by shaunsingh** [comment]
I think nyoom might be broken on dev versions, I'll look into it
