### ISSUE TITLE
Error after enabling some language modules

### ISSUE THREAD

**Issue by coder1044324** [shaunsingh/nyoom.nvim#72]
Enabled some modules (by uncommenting cc, java, latex, python) in modules.fnl under lang, then running "./nyoom sync" led to this error:
```
Synchronizing your config with Nyoom Nvim

nyoom version c58b0df
NVIM v0.8.0-dev-758-g711ef4eac
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by ___@___-MBP-2

Clearing cache
Error detected while processing /Users/___/.config/nvim/init.lua:
E5113: Error while calling lua chunk: module 'packages' not found:Compile error in /Users/___/.config/nvim/fnl/packages.fnl:9:0
  module not found fnl.modules

^[[7m(include :fnl.modules)^[[0m
	no field package.preload['packages']
	no file './packages.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/packages.lua'
	no file '/usr/local/share/lua/5.1/packages.lua'
	no file '/usr/local/share/lua/5.1/packages/init.lua'
	no file '/opt/homebrew/share/lua/5.1/packages.lua'
	no file '/opt/homebrew/share/lua/5.1/packages/init.lua'
	no file './packages.so'
	no file '/usr/local/lib/lua/5.1/packages.so'
	no file '/opt/homebrew/lib/lua/5.1/packages.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: at 0x01032ee2d4
	[C]: in function 'require'
	/Users/___/.config/nvim/init.lua:2: in main chunkError detected while processing command line:
E5108: Error executing lua [string ":lua"]:1: module 'packages' not found:Compile error in /Users/___/.config/nvim/fnl/packages.fnl:9:0
  module not found fnl.modules

^[[7m(include :fnl.modules)^[[0m
	no field package.preload['packages']
	no file './packages.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/packages.lua'
	no file '/usr/local/share/lua/5.1/packages.lua'
	no file '/usr/local/share/lua/5.1/packages/init.lua'
	no file '/opt/homebrew/share/lua/5.1/packages.lua'
	no file '/opt/homebrew/share/lua/5.1/packages/init.lua'
	no file './packages.so'
	no file '/usr/local/lib/lua/5.1/packages.so'
	no file '/opt/homebrew/lib/lua/5.1/packages.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk
E5108: Error executing lua [string ":lua"]:1: module 'packer' not found:
	no field package.preload['packer']
	no file './packer.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/packer.lua'
	no file '/usr/local/share/lua/5.1/packer.lua'
	no file '/usr/local/share/lua/5.1/packer/init.lua'
	no file '/opt/homebrew/share/lua/5.1/packer.lua'
	no file '/opt/homebrew/share/lua/5.1/packer/init.lua'
	no file './packer.so'
	no file '/usr/local/lib/lua/5.1/packer.so'
	no file '/opt/homebrew/lib/lua/5.1/packer.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk
```

At this point it does nothing at all, so I just had to keyboard interrupt. However now opening any file (the nyoom bash file for example), it is apparent that all the styling/features from nyoom have gone. 
<img width="1728" alt="Screenshot 2022-10-20 at 01 27 58" src="https://user-images.githubusercontent.com/116232390/196829109-80d693f0-6048-4cad-b799-6ba6afa7b252.png">
(now it is as above)

Also, I get this "module not found" error (red text in screenshot below) when I open modules.fnl:
<img width="1728" alt="Screenshot 2022-10-20 at 01 31 12" src="https://user-images.githubusercontent.com/116232390/196829299-7499fb86-3642-4f73-a9b8-ffbd141dcfd3.png">

Again, any help here would be appreciated.

**Comment by coder1044324** [comment]
When I ran nyoom sync, I had to be in `~/.config/nvim/bin`, otherwise it wouldn't run in fact.
I also just ran nyoom sync again it threw the same error as above.

btw, this is the perfect configuration for me, just wanted to say thank you for making it! ((:

**Comment by shaunsingh** [comment]
I would cd to `/.config/nvim` and then run `bin/nyoom sync`

I'll add better instructions to the README, plus I'm horribly abusing fennel's macro system and `include` feature which I should fix in the future, that'll eventually fix the `module 'packages' not found` error

**Comment by coder1044324** [comment]
Yes, that works now with no errors and installed things seem to be working fine.
Got you, so for the moment should I ignore those errors?

Also, wanted to ask how to change between the dark and light themes. I went into `~/.config/nvim/fnl/modules/config/default/config.fnl` and under ;;colorscheme, there is
```
;; colorscheme
(nyoom-module-p! nyoom
 (do
   (set! guifont "Scientifica:h15")
   (set! background :dark)
   (set! termguicolors)))
```
and after changing dark to light, then saving and exiting, the colours go weird and functionality is affected. 
<img width="1728" alt="Screenshot 2022-10-21 at 14 38 00" src="https://user-images.githubusercontent.com/116232390/197209253-5f9c4fa8-597d-40f5-b930-68122866ba47.png">
Do you have any ideas about what could be causing this? Once I run nyoom sync, it somehow fixes the colors, but the background is still light?!
<img width="1728" alt="Screenshot 2022-10-21 at 14 40 17" src="https://user-images.githubusercontent.com/116232390/197209709-8cdaa078-c80a-46fa-951e-e74f4c3f44a2.png">

**Comment by shaunsingh** [comment]
I temporarily removed support for the background-based-colorscheme because I was unhappy with how the light theme looked, I'll add it back with fixed colors soon

**Comment by coder1044324** [comment]
Ok, thanks for telling me. I'll look out for the update, thanks again for all of your help!
