### ISSUE TITLE
Error running config for indent-blankline.nvim

### ISSUE THREAD

**Issue by hsheikhali1** [shaunsingh/nyoom.nvim#81]
I installed the indent-blankline.nvim package but it keeps erroring out when I launch nyoom. Any ideas why this could be happening?

**Comment by luxus** [comment]
you maybe should post the error, and how exactly you installed the plugin?

**Comment by hsheikhali1** [comment]
Here is the error I get when I launch vim

![error](https://user-images.githubusercontent.com/14851850/204067269-d12275b9-e5f3-4511-8735-dbcffb784702.png)

This is how I installed it - just using the modules.fnl file
![error-modules](https://user-images.githubusercontent.com/14851850/204067270-7b365449-53e0-4e52-be01-2a1ee0ca2c8e.png)

**Comment by shaunsingh** [comment]
Fixed locally, I'll push it (along with some other fixes) soon
