### ISSUE TITLE
make the `map!` macro set keybindings via which-key.nvim

### ISSUE THREAD

**Issue by wizard-28** [shaunsingh/nyoom.nvim#9]
The current `map!` macro doesn't set the bindings via which-key.nvim, but thru the NeoVim Lua API. So the keybindings don't have a description attached with them when they're viewed thru the which-key pop-up.

**Comment by shaunsingh** [comment]
I'll rewrite the `map!` macro to use the which-key plugin soon, this should also help remove the `neovim-nightly` dependency for new users

**Comment by wizard-28** [comment]
@shaunsingh any updates on this?

**Comment by Bignig-Crino** [comment]
> The current `map!` macro doesn't set the bindings via which-key.nvim, but thru the NeoVim Lua API. So the keybindings don't have a description attached with them when they're viewed thru the which-key pop-up.

I second it

**Comment by shaunsingh** [comment]
@wizard-28 working on it

**Comment by shaunsingh** [comment]
I added a `doc-map!` macro to help with this. It doesn't add the binding, just documents it within which-key. You still need to use `map!` to map bindings, I hope this is a good solution. 

ex:
```
;; Mappings
(map! [n] "<leader>:" "<cmd>Telescope commands<CR>")
(map! [n] :<leader><space> "<cmd>Telescope find_files<CR>")

;; Document top level keys with which-key
(doc-map! :n "<leader>:" :silent :M-x)
(doc-map! :n :<leader><space> :silent "Project Fuzzy Search")
```
